{
    'name': 'Asset Management',
    "version": "1.0",
    'summary': 'Manage company assets, transfers, maintenance, and depreciation.',
    'description': """
        Streamline your Fixed asset lifecycle management with our comprehensive Odoo module. Track assets, automate depreciation, manage maintenance, and handle transfers effortlessly. Generate detailed reports, monitor warranties, and optimize asset utilization. User-friendly interface ensures easy adoption. Suitable for businesses of all sizes, this module empowers you to make informed decisions and maximize the value of your assets.
    """,
    'category': 'Operations',
    'depends': ['base', 'product', 'hr', 'account', 'account_asset', 'purchase', 'stock', 'mail', 'maintenance'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'wizard/asset_label_wizard_view.xml',
        'wizard/asset_warranty_wizard_views.xml',
        'wizard/asset_dashboard_wizard_views.xml',
        'report/asset_label_report.xml',
        'report/asset_label_templates.xml',
        'report/asset_template_templates.xml',
        'views/asset_views.xml',
        'views/asset_vendor_views.xml',
        'views/asset_disposal_views.xml',
        'views/asset_report.xml',
        'views/account_asset_views.xml',
        'views/stock_movement_report_views.xml',
        'views/stock_picking_views.xml'
    ],
    'assets': {
        'web.report_assets_common': [
            'asset_management/static/src/scss/report_label_sheet.scss',
        ],
    },
    'images': ['static/description/main_screenshot.png', 'static/description/formate_screenshot_1.png',
               'static/description/formate_screenshot_2.png', 'static/description/formate_screenshot_3.png',
               'static/description/formate_screenshot_4.png', 'static/description/formate_screenshot_5.png',
               'static/description/formate_screenshot_6.png', 'static/description/formate_screenshot_7.png'],
    'application': True,
    'installable': True,
    'price': 40,
    'currency': 'USD',
    'license': 'OPL-1',
    'author': 'Processdrive India Pvt Ltd.',
    'website': 'https://processdrive.com',
    'post_init_hook': 'post_migrate_resync_serials',
    'post_migrate': 'post_migrate_resync_serials',
}
